version: '3.8'


services:
  nginx:
    image: nginx:latest
    container_name: formulaire_nginx
    ports:
      - "8092:80" # Expose le port 8092 pour accéder au serveur
    volumes:
      - ./Formulaire:/usr/share/nginx/html:ro # Monte le dossier ExerciceFormulaire
      - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro # Utilise la configuration personnalisée
    depends_on:
      - php # Attendre que PHP-FPM soit prêt avant de démarrer Nginx
    restart: always


  php:
    image: php:8.1-fpm # PHP avec support FPM
    container_name: formulaire_php
    volumes:
      - ./Formulaire:/usr/share/nginx/html # Monte le même dossier pour PHP-FPM
    restart: always
